[build-system]
requires = ["flit_core>=3.12,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "uranos_project_os"
authors = [{name = "URANOS GROUP"}]
description = "Project execution and control for URANOS photovoltaic projects"
requires-python = ">=3.14"
readme = "README.md"
dynamic = ["version"]
dependencies = []

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"

[tool.flit.module]
name = "uranos_project_os"

[tool.ruff]
line-length = 110
target-version = "py314"

