"""Actual captured browser fixture envelopes must match the server's allowlist.

This test is not a live Frappe integration test. The artifact is regenerated by
tests/browser/field_qa.mjs, so a frontend/server schema drift is reviewable.
"""
import io
import json
from pathlib import Path

from PIL import Image

import pytest
from uranos_project_os.domain.offline import validate_envelope


def test_captured_browser_envelopes_match_domain_and_valid_images():
    artifact = Path(__file__).parents[1] / "evidence" / "browser" / "envelopes.json"
    if not artifact.exists():
        pytest.skip("Browser fixture envelopes.json not yet generated by tests/browser/field_qa.mjs")
    envelopes = [validate_envelope(raw) for raw in json.loads(artifact.read_text(encoding="utf-8"))]
    assert {row.operation for row in envelopes} == {"progress", "daily_report", "inspection", "kit_request", "kit_return"}
    progress = [row.payload for row in envelopes if row.operation == "progress"]
    assert any(row.get("kit_issue") == "DEMO-PV-A-ISSUE-1" for row in progress)
    assert any(row.get("cable_reel") == "DEMO-PV-A-REEL-1" for row in progress)
    assert any(not row.get("kit_issue") and not row.get("cable_reel") for row in progress)
    for envelope in envelopes:
        assert "qty_verified" not in envelope.payload
        assert not (envelope.payload.get("kit_issue") and envelope.payload.get("cable_reel"))
        for attachment in envelope.attachments:
            with Image.open(io.BytesIO(attachment.content)) as image:
                image.verify()
