/** Run: node tests/browser/field_qa.mjs. This verifies UI/offline transport only.
 * Install `playwright` locally or supply PLAYWRIGHT_MODULE to an installed path. */
import {createRequire} from "node:module";
import assert from "node:assert/strict";
import {mkdir,writeFile} from "node:fs/promises";
import {fileURLToPath} from "node:url";
import path from "node:path";
import {createFixtureServer} from "./fixture_server.mjs";
const require = createRequire(import.meta.url);
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const evidenceDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../evidence/browser");
await mkdir(evidenceDir,{recursive:true});
const fixture = await createFixtureServer();
const browser = await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE} : {})});
const context = await browser.newContext({viewport:{width:1440,height:1000},locale:"fr-FR"});
const page = await context.newPage();
const errors = []; const checks = [];
page.on("pageerror",error => errors.push(error.message));
const mark = name => {checks.push(name);process.stdout.write(`PASS ${name}\n`);};
const ready = async () => {await page.locator(".project-card").first().waitFor();};
const view = async name => {await page.locator(`[data-view="${name}"]`).click();await page.waitForTimeout(80);};
const fill = async values => {for (const [name,value] of Object.entries(values)) {const locator=page.locator(`[name="${name}"]`);if (await locator.evaluate(element => element.tagName === "SELECT")) await locator.selectOption(value);else await locator.fill(value);}};
const save = async () => {await page.locator("#next").click();await page.locator('button[name="save"]').click();await page.locator(".queue-card").first().waitFor();};
const png = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAADElEQVR4nGMQsq8CAAEyAMxInoTCAAAAAElFTkSuQmCC","base64");
try {
  await page.goto(fixture.url + "/uranos");await ready();
  assert.equal(await page.locator(".project-card").count(),3);
  assert.match(await page.locator('.project-card[data-project="DEMO-PV-C"]').innerText(),/A COMPLETER/);
  assert.equal(await page.locator("[data-view]").count(),7);
  await page.screenshot({path:path.join(evidenceDir,"desktop-fr.png"),fullPage:true});
  mark("six authorized role views; unknown baseline never shown as zero/green");
  await page.locator('[data-project="DEMO-PV-A"]').click();await page.locator(".metric.verified").waitFor();
  assert.match(await page.locator(".metric.verified").innerText(),/35/);
  assert.match(await page.locator(".metric.planned").innerText(),/49/);
  assert.match(await page.locator(".metric.materials").innerText(),/80/);
  await page.locator("[data-package]").first().click();
  assert.match(await page.locator("#dialog").innerText(),/600/);
  assert.match(await page.locator("#dialog a").first().getAttribute("href"),/work_package=DEMO-PV-A-WP030/);
  await page.locator(".close-dialog").click();
  mark("separate verified/planned/material KPIs and work-package evidence drill-through");
  await view("team");await page.locator('[data-capture="progress"]').click();
  await fill({work_package:"DEMO-PV-A-WP030",activity:"BATTAGE",zone:"Z01",crew:"TEAM-DEMO",qty_reported:"12"});
  await page.locator("#next").click();
  assert.equal(await page.locator('[name="kit_issue"] option[value="DEMO-PV-A-ISSUE-2"]').count(),0);
  await page.locator('[name="kit_issue"]').selectOption("DEMO-PV-A-ISSUE-1");
  assert.equal(await page.locator('[name="cable_reel"]').isDisabled(),true);
  await page.locator('[name="evidence"]').setInputFiles({name:"preuve-demo.png",mimeType:"image/png",buffer:png});
  await context.setOffline(true);
  await page.locator('button[name="save"]').click();await page.locator(".queue-card").waitFor();
  assert.match(await page.locator(".queue-card").innerText(),/Brouillon local/);
  assert.equal(await page.locator("#sync-all").isDisabled(),true);
  const dbCheck = await page.evaluate(async () => {
    const databases = await indexedDB.databases();const name=databases[0].name;
    const db=await new Promise(resolve => {const request=indexedDB.open(name);request.onsuccess=() => resolve(request.result);});
    const rows=await new Promise(resolve => {const request=db.transaction("drafts").objectStore("drafts").getAll();request.onsuccess=() => resolve(request.result);});db.close();
    return {keys:Object.keys(rows[0]),encrypted:rows[0].ciphertext instanceof ArrayBuffer,raw:JSON.stringify(rows)};
  });
  assert.deepEqual(dbCheck.keys.sort(),["ciphertext","iv","uuid"]);
  assert.equal(dbCheck.encrypted,true);assert.equal(dbCheck.raw.includes("TEAM-DEMO"),false);
  mark("offline installation and image saved as AES-GCM ciphertext; sync requires connection");
  await context.setOffline(false);
  fixture.state.mode="lost-response";
  await page.locator("#sync-all").click();await page.locator(".queue-state.queued").waitFor();
  assert.equal(fixture.state.receipts.size,1);
  await page.locator("[data-sync]").click();await page.locator(".queue-state.synced").waitFor();
  assert.equal(fixture.state.receipts.size,1);
  const received=[...fixture.state.receipts.values()][0];
  assert.equal(received.envelope.payload.qty_reported,"12");
  assert.equal(received.envelope.payload.qty_verified,undefined);
  assert.equal(received.envelope.payload.kit_issue,"DEMO-PV-A-ISSUE-1");
  assert.equal(received.envelope.payload.cable_reel,undefined);
  assert.equal(received.envelope.attachments.length,1);assert.equal(received.envelope.attachments[0].sha256.length,64);
  assert.equal(fixture.state.submits.length,0);assert.equal(fixture.state.verified.length,0);
  mark("lost-response retry retains UUID, one fixture receipt, full evidence and draft-only result");
  await page.locator("[data-submit]").click();await page.waitForFunction(() => !document.querySelector("[data-submit]"));
  assert.equal(fixture.state.submits.length,1);
  mark("separate explicit submit to controller after server draft synchronization");
  await view("team");await page.locator('[data-capture="daily_report"]').click();
  await fill({site:"SITE-DEMO",manpower:"8",equipment:"ENGIN-DEMO",weather:"Clair"});await save();
  fixture.state.mode="conflict";await page.locator("#sync-all").click();await page.locator(".queue-state.conflict").waitFor();
  await page.locator(".queue-card").filter({has:page.locator(".queue-state.conflict")}).locator("[data-review]").click();
  assert.match(await page.locator("#dialog").innerText(),/contenu original/);await page.locator(".close-dialog").click();
  fixture.state.mode="reject";await page.locator(".queue-card").filter({has:page.locator(".queue-state.conflict")}).locator("[data-sync]").click();await page.locator(".queue-state.rejected").waitFor();
  mark("conflict and rejection are explicit; original envelope/UUID preserved");
  fixture.state.mode="ok";
  await view("store");await page.locator('[data-capture="kit_request"]').click();
  await fill({work_package:"DEMO-PV-A-WP030",kit_template:"DEMO-PV-A-KIT",qty_kits:"2",from_warehouse:"DEMO-PV-A-Available",to_warehouse:"DEMO-PV-A-WIP",activity:"STRUCTURE",crew:"TEAM-DEMO"});await save();
  await view("store");await page.locator('[data-capture="kit_return"]').click();
  await fill({kit_issue:"ISSUE-DEMO",to_warehouse:"DEMO-PV-A-Available",row_item_code:"BOLT-DEMO",row_qty:"4",row_uom:"Nos"});await save();
  await view("quality");await page.locator('[data-capture="inspection"]').click();
  await fill({work_package:"DEMO-PV-A-WP030",zone:"Z01",inspection_type:"PILING",row_check:"PROC-DEMO-1",row_result:"Pass"});await save();
  assert.equal(await page.locator(".queue-card").count(),5);
  await page.locator("#sync-all").click();await page.waitForFunction(() => document.querySelectorAll(".queue-state.synced").length === 4);
  assert.deepEqual([...fixture.state.receipts.values()].map(row => row.envelope.operation).sort(),["inspection","kit_request","kit_return","progress"]);
  await page.locator(".queue-card").filter({has:page.locator(".queue-state.rejected")}).locator("[data-sync]").click();
  await page.waitForFunction(() => document.querySelectorAll(".queue-state.synced").length === 5);
  assert.deepEqual([...fixture.state.receipts.values()].map(row => row.envelope.operation).sort(),["daily_report","inspection","kit_request","kit_return","progress"]);
  assert.equal(fixture.state.submits.length,1);
  mark("five capture forms produce exact envelopes; kit draft never posts stock");
  const wrongKey = await page.evaluate(async () => {
    const {openQueue}=await import("/assets/uranos_project_os/field/queue.js");
    const queue=await openQueue("controller-a@example.invalid",btoa(String.fromCharCode(...new Uint8Array(32).fill(2))));
    try {await queue.all();return false;} catch {return true;} finally {queue.close();}
  });
  assert.equal(wrongKey,true);
  mark("different user's encryption key cannot decrypt persisted drafts");
  await view("controller");await page.locator('[data-verify="PROGRESS-DEMO-1"]').waitFor();
  assert.equal(await page.locator('[data-verify="PROGRESS-SELF"]').count(),0);
  await page.locator('[data-verify="PROGRESS-DEMO-1"]').click();await fill({qty_verified:"8"});await page.locator("#verify-form button").click();
  await page.waitForFunction(() => !document.querySelector("#dialog[open]"));
  assert.equal(fixture.state.verified[0].qty_verified,"8");
  mark("online independent partial verification control; self-approval action hidden");
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(evidenceDir,"mobile-fr.png"),fullPage:true});
  await page.locator("#language").click();assert.equal(await page.locator("html").getAttribute("dir"),"rtl");
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
  await view("team");await page.locator('[data-capture="progress"]').click();
  assert.equal(await page.locator("#dialog").evaluate(element => element.scrollWidth <= element.clientWidth),true);
  await page.screenshot({path:path.join(evidenceDir,"mobile-ar-form.png"),fullPage:true});
  await fill({work_package:"DEMO-PV-A-WP030",activity:"BATTAGE",zone:"Z01",crew:"TEAM-DEMO",qty_reported:"1"});
  await page.locator("#next").click();
  assert.equal(await page.locator("#dialog").evaluate(element => element.scrollWidth <= element.clientWidth),true);
  await page.screenshot({path:path.join(evidenceDir,"mobile-ar-allocation.png"),fullPage:true});
  await page.locator(".close-dialog").click();await page.locator("#language").click();
  mark("mobile 390px FR and Arabic RTL layouts/forms fit viewport");
  await page.goto(fixture.url+"/assets/uranos_project_os/field/offline.html");await ready();
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.reload();await ready();
  await context.setOffline(true);await page.reload();await page.locator("#retry-boot").waitFor();
  assert.equal(await page.locator(".queue-card").count(),0);
  assert.equal((await page.content()).includes("TEAM-DEMO"),false);
  await context.setOffline(false);await page.locator("#retry-boot").click();await ready();await view("queue");
  assert.equal(await page.locator(".queue-card").count(),5);
  const cachePaths = await page.evaluate(async () => {const result=[];for(const key of await caches.keys())for(const request of await (await caches.open(key)).keys())result.push(new URL(request.url).pathname);return result;});
  assert.equal(cachePaths.every(value => value.startsWith("/assets/uranos_project_os/field/")),true);
  assert.equal(cachePaths.some(value => value.includes("api/") || value === "/uranos" || value.includes("private")),false);
  mark("offline cold start locks without data; online reauthentication recovers drafts; cache static-only");
  fixture.state.user="user-b@example.invalid";await page.reload();await ready();await view("queue");
  assert.equal(await page.locator(".queue-card").count(),0);
  fixture.state.user="controller-a@example.invalid";await page.reload();await ready();await view("queue");
  assert.equal(await page.locator(".queue-card").count(),5);
  mark("user switch cannot display prior user's drafts; original user can recover encrypted queue");
  fixture.state.keyUnavailable=true;await page.reload();await ready();
  assert.equal(await page.locator(".project-card").count(),3);
  assert.equal(await page.locator("#notice.bad").count(),1);
  fixture.state.keyUnavailable=false;
  mark("read-only dashboard remains usable when encryption-key service unavailable");
  await page.reload();await ready();await view("team");await page.locator('[data-capture="daily_report"]').click();
  await fill({site:"RACE-DEMO"});await save();
  const receiptsBeforeRace=fixture.state.receipts.size;
  await page.route("**/api/method/uranos_project_os.services.api.bootstrap",async route => {
    const response=await route.fetch();fixture.state.user="user-b@example.invalid";await route.fulfill({response});
  });
  await page.locator("#sync-all").click();await page.locator("#retry-boot").waitFor();
  assert.equal(fixture.state.receipts.size,receiptsBeforeRace);
  assert.equal(await page.locator(".queue-card").count(),0);
  await page.unroute("**/api/method/uranos_project_os.services.api.bootstrap");
  fixture.state.user="controller-a@example.invalid";await page.locator("#retry-boot").click();await ready();await view("queue");
  assert.equal(await page.locator(".queue-card").count(),6);
  mark("actor changes between bootstrap and POST: expected-user header rejects replay and locks UI");
  await view("team");await page.locator('[data-capture="progress"]').click();
  await fill({work_package:"DEMO-PV-A-WP030",activity:"NO-ALLOCATION",zone:"Z01",crew:"TEAM-DEMO",qty_reported:"1"});
  await save();
  await view("team");await page.locator('[data-capture="progress"]').click();
  await fill({work_package:"DEMO-PV-A-WP030",activity:"CABLE",zone:"Z01",crew:"TEAM-DEMO",qty_reported:"2"});
  await page.locator("#next").click();
  await page.locator('[name="cable_reel"]').selectOption("DEMO-PV-A-REEL-1");
  assert.equal(await page.locator('[name="kit_issue"]').isDisabled(),true);
  await page.evaluate(() => {document.querySelector('[name="kit_issue"]').value="DEMO-PV-A-ISSUE-1";});
  await page.locator('button[name="save"]').click();
  assert.match(await page.locator("#form-error").innerText(),/jamais les deux/);
  await page.evaluate(() => {document.querySelector('[name="kit_issue"]').value="";});
  await page.locator('button[name="save"]').click();await page.locator("#sync-all").click();
  await page.waitForFunction(() => document.querySelectorAll(".queue-state.synced").length === 8);
  const progressPayloads=[...fixture.state.receipts.values()].filter(row=>row.envelope.operation==="progress").map(row=>row.envelope.payload);
  assert.ok(progressPayloads.some(row=>row.kit_issue==="DEMO-PV-A-ISSUE-1" && !row.cable_reel));
  assert.ok(progressPayloads.some(row=>row.cable_reel==="DEMO-PV-A-REEL-1" && !row.kit_issue));
  assert.ok(progressPayloads.some(row=>row.activity==="NO-ALLOCATION" && !row.kit_issue && !row.cable_reel));
  assert.equal(progressPayloads.some(row=>row.kit_issue && row.cable_reel),false);
  mark("progress allocation stays optional, kit/reel options scoped; double allocation rejected before persistence");
  const originalRoles=[...fixture.state.roles];
  fixture.state.roles=["QA QC"];await page.reload();await page.locator(".pending-row").first().waitFor();
  assert.equal(await page.locator("[data-verify]").count(),0);
  fixture.state.roles=["Project Manager"];await page.reload();await ready();await view("quality");await page.locator(".pending-row").first().waitFor();
  assert.equal(await page.locator("[data-verify]").count(),0);
  await view("controller");assert.equal(await page.locator("[data-verify]").count(),0);
  fixture.state.roles=["Site Controller"];await page.reload();await page.locator("[data-verify]").waitFor();
  assert.equal(await page.locator("[data-verify]").count(),1);
  fixture.state.roles=originalRoles;await page.reload();await ready();
  mark("QA-only and Project-Manager-only views cannot verify progress; Site Controller retains independent action");
  await view("team");
  await Promise.all([page.waitForResponse(response=>response.url().includes("api.project_context?project=DEMO-PV-B")),page.locator("#project-select").selectOption("DEMO-PV-B")]);
  await page.locator('[data-capture="daily_report"]').click();await fill({site:"REVOKED-B-DRAFT"});await save();
  const revokedCard=page.locator(".queue-card").filter({has:page.locator(".project-code",{hasText:"DEMO-PV-B"})});
  const revokedUUID=await revokedCard.locator(".uuid bdi").innerText();
  await context.setOffline(true);fixture.state.allowedProjects=["DEMO-PV-A","DEMO-PV-C"];
  assert.equal(await revokedCard.count(),1);
  await context.setOffline(false);await page.locator("#retry-boot").waitFor();
  await page.locator("#retry-boot").click();await ready();await view("queue");
  assert.equal(await page.locator(".queue-card").count(),8);
  assert.equal((await page.locator("#content").innerText()).includes("DEMO-PV-B"),false);
  const requestCount=fixture.state.requests.filter(row=>row.method==="offline.synchronize").length;
  await page.locator("#sync-all").click();await page.waitForTimeout(100);
  assert.equal(fixture.state.requests.filter(row=>row.method==="offline.synchronize").length,requestCount);
  await view("team");await page.locator('[data-capture="daily_report"]').click();await fill({site:"AUTHORIZED-A-DRAFT"});await save();
  await page.locator("[data-sync]").evaluate((button,uuid)=>{button.dataset.sync=uuid;},revokedUUID);
  await page.locator("[data-sync]").click();await page.waitForTimeout(100);
  assert.equal(fixture.state.requests.filter(row=>row.method==="offline.synchronize").length,requestCount);
  fixture.state.allowedProjects=["DEMO-PV-A","DEMO-PV-B","DEMO-PV-C"];
  await page.reload();await ready();await view("queue");
  assert.equal(await page.locator(".queue-card").count(),10);
  assert.equal(await page.locator(".queue-card").filter({has:page.locator(".project-code",{hasText:"DEMO-PV-B"})}).count(),1);
  mark("same-user project revocation hides drafts and blocks bulk/tampered replay; restored scope recovers preserved ciphertext");
  fixture.state.roles=["Finance Controller"];
  await page.route("**/api/method/uranos_project_os.services.api.bootstrap",async route => {
    const response=await route.fetch();const data=await response.json();data.message.finance_allowed=true;
    await route.fulfill({response,json:data});
  });
  await page.route("**/api/method/uranos_project_os.services.api.dashboard?*",async route => {
    const response=await route.fetch();const data=await response.json();
    data.message.costs=[{work_package:"FINANCE-DEMO-WP",currency:"DEMO",budget:100,committed:40,forecast:95}];
    await route.fulfill({response,json:data});
  });
  await page.reload();await ready();
  assert.equal(await page.locator('[data-view="control"]').count(),1);
  assert.equal(await page.locator('[data-view="team"], [data-view="store"], [data-view="controller"]').count(),0);
  await page.locator('[data-project="DEMO-PV-A"]').click();
  await page.getByText("FINANCE-DEMO-WP",{exact:true}).waitFor();
  assert.equal(await page.locator("[data-capture], [data-verify]").count(),0);
  mark("Finance-Controller-only session sees scoped control/cost view without field write actions");
  assert.deepEqual(errors,[]);
  await writeFile(path.join(evidenceDir,"envelopes.json"),JSON.stringify([...fixture.state.receipts.values()].map(row => row.envelope),null,2));
  await writeFile(path.join(evidenceDir,"result.json"),JSON.stringify({evidence_level:"browser UI against explicitly synthetic HTTP fixtures; NOT live Frappe/ERPNext E2E",timestamp:new Date().toISOString(),browser:browser.version(),checks,page_errors:errors,screenshots:["desktop-fr.png","mobile-fr.png","mobile-ar-form.png","mobile-ar-allocation.png"]},null,2));
  process.stdout.write(`\n${checks.length} browser checks passed. Not live ERPNext integration evidence.\n`);
} finally {await context.close();await browser.close();await fixture.close();}
